# Generated by Django 6.0.3 on 2026-03-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauElimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numéro de bordereau')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('service_producteur', models.CharField(max_length=200, verbose_name='Service producteur')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_VALIDATION', 'En attente de visa archivistique (DAS)'), ('VISA_OBTENU', 'Visa obtenu — Élimination autorisée'), ('EXECUTE', 'Élimination exécutée'), ('REJETE', 'Rejeté par la DAS')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('motif', models.TextField(verbose_name="Motif d'élimination")),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('visa_das', models.BooleanField(default=False, help_text='Visa de la Direction des Archives du Sénégal — obligatoire avant toute élimination', verbose_name='Visa DAS obtenu')),
                ('date_visa', models.DateField(blank=True, null=True, verbose_name='Date du visa')),
                ('reference_visa', models.CharField(blank=True, max_length=100, verbose_name='Référence du visa')),
                ('date_elimination', models.DateField(blank=True, null=True, verbose_name="Date d'élimination effective")),
            ],
            options={
                'verbose_name': "Bordereau d'élimination",
                'verbose_name_plural': "Bordereaux d'élimination",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BordereauVersement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numéro de bordereau')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('service_versant', models.CharField(max_length=200, verbose_name='Service versant')),
                ('service_destinataire', models.CharField(default='Archives nationales du Sénégal', max_length=200, verbose_name='Service destinataire')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('EXECUTE', 'Exécuté'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
            ],
            options={
                'verbose_name': 'Bordereau de versement',
                'verbose_name_plural': 'Bordereaux de versement',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CategorieDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ADM', 'Administratif et institutionnel'), ('PED', 'Gestion académique et pédagogique'), ('SCI', 'Scientifique et de recherche'), ('GEO', 'Géologique et minier'), ('TER', 'Terrain et technique'), ('PAR', 'Partenariats et industrie'), ('FRH', 'Financier et ressources humaines'), ('PAT', 'Patrimonial et historique')], max_length=10, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(db_index=True, editable=False, help_text='Format : ENSMG-AAAA-CODE-XXXXXXXX', max_length=60, unique=True, verbose_name='Identifiant unique')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('producteur', models.CharField(max_length=200, verbose_name='Service producteur')),
                ('date_creation', models.DateField(verbose_name='Date de création du document')),
                ('date_reception', models.DateField(blank=True, null=True, verbose_name='Date de réception')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement dans le système")),
                ('description', models.TextField(blank=True, verbose_name='Description / Résumé')),
                ('mots_cles', models.TextField(blank=True, help_text='Séparés par des virgules', verbose_name='Mots-clés')),
                ('langue', models.CharField(default='fr', max_length=10, verbose_name='Langue')),
                ('statut', models.CharField(choices=[('COURANT', 'Archive courante'), ('INTERMEDIAIRE', 'Archive intermédiaire'), ('DEFINITIF', 'Archive définitive'), ('EN_VERSEMENT', 'En cours de versement'), ('VERSE', 'Versé aux Archives nationales'), ('EN_ELIMINATION', "En cours d'élimination"), ('ELIMINE', 'Éliminé')], db_index=True, default='COURANT', max_length=20, verbose_name='Statut')),
                ('confidentialite', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNE', 'Usage interne'), ('CONFIDENTIEL', 'Confidentiel'), ('SECRET', 'Secret')], default='INTERNE', max_length=20, verbose_name='Niveau de confidentialité')),
                ('support', models.CharField(choices=[('NUMERIQUE', 'Numérique'), ('PAPIER', 'Papier'), ('MIXTE', 'Mixte (papier + numérique)')], default='NUMERIQUE', max_length=10, verbose_name='Support')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='archives/%Y/%m/', verbose_name='Fichier numérique')),
                ('nom_fichier_original', models.CharField(blank=True, max_length=255, verbose_name='Nom du fichier original')),
                ('taille_fichier', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('empreinte_sha256', models.CharField(blank=True, help_text="Garantie d'intégrité du fichier numérique", max_length=64, verbose_name='Empreinte SHA-256')),
                ('localisation_physique', models.CharField(blank=True, help_text='Ex : Bâtiment A, Salle 12, Étagère 3, Boîte 7', max_length=300, verbose_name='Localisation physique')),
                ('date_fin_dua', models.DateField(blank=True, help_text='Calculée automatiquement à partir du tableau de gestion', null=True, verbose_name='Date de fin de DUA')),
                ('sort_final', models.CharField(choices=[('CONSERVATION', 'Conservation définitive'), ('ELIMINATION', 'Élimination'), ('TRI', 'Tri'), ('EN_ATTENTE', 'En attente de décision')], default='EN_ATTENTE', max_length=20, verbose_name='Sort final')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Document d'archives",
                'verbose_name_plural': "Documents d'archives",
                'ordering': ['-date_enregistrement'],
                'permissions': [('can_eliminate', "Peut déclencher une procédure d'élimination"), ('can_verse', 'Peut effectuer un versement'), ('can_view_confidentiel', 'Peut consulter les documents confidentiels'), ('can_view_secret', 'Peut consulter les documents secrets')],
            },
        ),
        migrations.CreateModel(
            name='MouvementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('CONSULTATION', 'Consultation'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('VERSEMENT', 'Versement'), ('ELIMINATION', 'Élimination'), ('TRANSFERT', 'Transfert'), ('RESTAURATION', 'Restauration'), ('TELECHARGEMENT', 'Téléchargement')], max_length=30, verbose_name='Action')),
                ('date_action', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date et heure')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('details', models.JSONField(default=dict, help_text='Valeurs avant/après pour les modifications', verbose_name='Détails')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date_action'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PlanClassement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Cote')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('niveau', models.PositiveSmallIntegerField(choices=[(1, 'Fonds'), (2, 'Série'), (3, 'Sous-série'), (4, 'Dossier')], verbose_name='Niveau hiérarchique')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Plan de classement',
                'verbose_name_plural': 'Plan de classement',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TableauGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé du type de document')),
                ('duree_courante', models.PositiveIntegerField(help_text='Durée en archives courantes', verbose_name='DUA courante (années)')),
                ('duree_intermediaire', models.PositiveIntegerField(default=0, help_text='Durée en archives intermédiaires', verbose_name='DUA intermédiaire (années)')),
                ('sort_final', models.CharField(choices=[('CONSERVATION', 'Conservation définitive'), ('ELIMINATION', 'Élimination'), ('TRI', 'Tri (conservation partielle)')], max_length=20, verbose_name='Sort final')),
                ('observations', models.TextField(blank=True, verbose_name='Observations / Références légales')),
            ],
            options={
                'verbose_name': 'Tableau de gestion (DUA)',
                'verbose_name_plural': 'Tableau de gestion (DUA)',
                'ordering': ['type_document', 'intitule'],
            },
        ),
    ]
