# Generated by Django 6.0.3 on 2026-03-11 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereauelimination',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bordereaux_elimination_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='bordereauversement',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bordereaux_versement_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='bordereauversement',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bordereaux_versement_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='document',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives.categoriedocument', verbose_name='Catégorie documentaire'),
        ),
        migrations.AddField(
            model_name='document',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='document',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='bordereauversement',
            name='documents',
            field=models.ManyToManyField(related_name='bordereaux_versement', to='archives.document', verbose_name='Documents versés'),
        ),
        migrations.AddField(
            model_name='bordereauelimination',
            name='documents',
            field=models.ManyToManyField(related_name='bordereaux_elimination', to='archives.document', verbose_name='Documents à éliminer'),
        ),
        migrations.AddField(
            model_name='mouvementdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='archives.document', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='mouvementdocument',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='planclassement',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.categoriedocument', verbose_name='Catégorie documentaire'),
        ),
        migrations.AddField(
            model_name='planclassement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='archives.planclassement', verbose_name='Rubrique parente'),
        ),
        migrations.AddField(
            model_name='document',
            name='plan_classement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives.planclassement', verbose_name='Cote de classement'),
        ),
        migrations.AddField(
            model_name='tableaugestion',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives.categoriedocument', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='document',
            name='tableau_gestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.tableaugestion', verbose_name='Tableau de gestion (DUA)'),
        ),
    ]
