# Generated by Django 6.0.3 on 2026-03-12 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('PHYSIQUE', 'Document physique (prêt avec bon)'), ('NUMERIQUE', 'Document numérique (accès temporaire 24h)')], max_length=20, verbose_name='Type de demande')),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('ACCORDEE', 'Accordée'), ('REFUSEE', 'Refusée'), ('CLOTUREE', 'Clôturée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif du refus')),
                ('duree_acces_heures', models.PositiveIntegerField(default=24, help_text='Pour les documents numériques uniquement. Défaut : 24h.', verbose_name="Durée d'accès (heures)")),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_pret', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_pret', to='archives.document', verbose_name='Document demandé')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par')),
            ],
            options={
                'verbose_name': 'Demande de prêt / accès',
                'verbose_name_plural': 'Demandes de prêt / accès',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DepotDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recepisse', models.CharField(editable=False, help_text='Généré automatiquement — preuve légale du dépôt.', max_length=30, unique=True, verbose_name='Numéro de récépissé')),
                ('fichier', models.FileField(upload_to='depots/%Y/%m/', verbose_name='Fichier déposé')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre du document')),
                ('date_reception', models.DateField(verbose_name='Date de réception du document')),
                ('description', models.TextField(blank=True, verbose_name='Description / Contexte')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('ARCHIVE', 'Archivé'), ('REJETE', 'Rejeté')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif du rejet')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots', to=settings.AUTH_USER_MODEL, verbose_name='Agent déposant')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.categoriedocument', verbose_name='Type de document (optionnel)')),
                ('document_archive', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depot_source', to='archives.document', verbose_name="Document d'archives créé")),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Dépôt de document',
                'verbose_name_plural': 'Dépôts de documents',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOUVEAU_DEPOT', 'Nouveau dépôt à traiter'), ('DEPOT_ARCHIVE', 'Votre dépôt a été archivé'), ('DEPOT_REJETE', 'Votre dépôt a été rejeté'), ('ACCES_ACCORDE', 'Accès accordé à un document'), ('ACCES_EXPIRE', 'Accès expiré'), ('DEMANDE_PRET', 'Nouvelle demande de prêt'), ('PRET_ACCORDE', 'Prêt accordé'), ('PRET_REFUSE', 'Prêt refusé'), ('PRET_RAPPEL', 'Rappel : retour de prêt attendu'), ('PRET_RETARD', 'Prêt en retard'), ('ALERTE_DUA', 'DUA échéant dans 30 jours'), ('DUA_ECHUE', 'DUA échue — action requise'), ('INTEGRITE_KO', 'Alerte intégrité fichier')], max_length=30, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lue', models.BooleanField(db_index=True, default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Lien de redirection')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.depotdocument', verbose_name='Dépôt lié')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.document', verbose_name='Document lié')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PretDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro de bon de prêt')),
                ('date_pret', models.DateField(auto_now_add=True, verbose_name='Date de prêt')),
                ('date_retour_prevue', models.DateField(verbose_name='Date de retour prévue')),
                ('date_retour_effective', models.DateField(blank=True, null=True, verbose_name='Date de retour effective')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard'), ('PERDU', 'Perdu / Non retourné')], db_index=True, default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('accorde_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets_accordes', to=settings.AUTH_USER_MODEL, verbose_name='Accordé par')),
                ('demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.demandepret', verbose_name="Demande d'origine")),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prets', to='archives.document', verbose_name='Document')),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prets', to=settings.AUTH_USER_MODEL, verbose_name='Emprunteur')),
            ],
            options={
                'verbose_name': 'Prêt de document',
                'verbose_name_plural': 'Prêts de documents',
                'ordering': ['-date_pret'],
            },
        ),
        migrations.CreateModel(
            name='RetentionJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif de la rétention')),
                ('autorite', models.CharField(help_text='Ex : Tribunal régional de Dakar, Cour des Comptes...', max_length=200, verbose_name='Autorité ordonnante')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence du texte juridique')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin (vide = indéfinie)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistrée par')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retentions', to='archives.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Rétention juridique',
                'verbose_name_plural': 'Rétentions juridiques',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='VerificationIntegrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verification', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de vérification')),
                ('resultat', models.CharField(choices=[('OK', 'Intégrité vérifiée ✓'), ('ECHOUE', 'Altération détectée ✗'), ('ERREUR', 'Erreur technique')], max_length=10, verbose_name='Résultat')),
                ('empreinte_calculee', models.CharField(blank=True, max_length=64, verbose_name='Empreinte SHA-256 calculée')),
                ('empreinte_reference', models.CharField(blank=True, max_length=64, verbose_name='Empreinte SHA-256 de référence')),
                ('message', models.TextField(blank=True, verbose_name='Message / Détails')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_integrite', to='archives.document', verbose_name='Document')),
                ('verifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': "Vérification d'intégrité",
                'verbose_name_plural': "Vérifications d'intégrité",
                'ordering': ['-date_verification'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='AccesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name="Début de l'accès")),
                ('date_fin', models.DateTimeField(blank=True, help_text='Laisser vide pour un accès permanent. 24h par défaut pour les numériques.', null=True, verbose_name="Fin de l'accès")),
                ('type_acces', models.CharField(choices=[('LECTURE', 'Lecture seule'), ('TELECHARGEMENT', 'Lecture + Téléchargement')], default='LECTURE', max_length=20, verbose_name="Type d'accès")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('motif', models.TextField(blank=True, verbose_name="Motif de l'accès")),
                ('accorde_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acces_accordes', to=settings.AUTH_USER_MODEL, verbose_name='Accordé par')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_speciaux', to='archives.document', verbose_name='Document')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Accès spécial document',
                'verbose_name_plural': 'Accès spéciaux documents',
                'ordering': ['-date_debut'],
                'unique_together': {('document', 'utilisateur')},
            },
        ),
    ]
