# Generated by Django 6.0.3 on 2026-03-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_provenance_initiale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NOUVEAU_DEPOT', 'Nouveau dépôt à traiter'), ('DEPOT_ARCHIVE', 'Votre dépôt a été archivé'), ('DEPOT_REJETE', 'Votre dépôt a été rejeté'), ('ACCES_ACCORDE', 'Accès accordé à un document'), ('ACCES_EXPIRE', 'Accès expiré'), ('DEMANDE_PRET', 'Nouvelle demande de prêt'), ('PRET_ACCORDE', 'Prêt accordé'), ('PRET_REFUSE', 'Prêt refusé'), ('PRET_RAPPEL', 'Rappel : retour de prêt attendu'), ('PRET_RETARD', 'Prêt en retard'), ('ALERTE_DUA', 'DUA échéant dans 30 jours'), ('DUA_ECHUE', 'DUA échue — action requise'), ('INTEGRITE_KO', 'Alerte intégrité fichier'), ('RECHERCHE_RECUE', 'Nouvelle demande de recherche documentaire'), ('RECHERCHE_ACCORDEE', 'Recherche traitée — document trouvé'), ('RECHERCHE_REFUSEE', 'Recherche — document non trouvé')], max_length=30, verbose_name='Type'),
        ),
    ]
