# Generated by Django 6.0.3 on 2026-03-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_messagerie_interne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='en_reponse_a',
            field=models.ForeignKey(blank=True, help_text='Renseigner uniquement pour un courrier DÉPART qui répond à un courrier ARRIVÉE', limit_choices_to={'sens': 'ARRIVEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='archives.courrier', verbose_name='En réponse au courrier arrivée'),
        ),
        migrations.AlterField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Si renseigné, le document est en corbeille (suppression logique). Purge automatique après 30 jours.', null=True, verbose_name='Mis en corbeille le'),
        ),
        migrations.AlterField(
            model_name='document',
            name='texte_extrait',
            field=models.TextField(blank=True, verbose_name='Texte extrait (OCR / indexation plein texte)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NOUVEAU_DEPOT', 'Nouveau dépôt à traiter'), ('DEPOT_ARCHIVE', 'Votre dépôt a été archivé'), ('DEPOT_REJETE', 'Votre dépôt a été rejeté'), ('ACCES_ACCORDE', 'Accès accordé à un document'), ('ACCES_EXPIRE', 'Accès expiré'), ('DEMANDE_PRET', 'Nouvelle demande de prêt'), ('PRET_ACCORDE', 'Prêt accordé'), ('PRET_REFUSE', 'Prêt refusé'), ('PRET_RAPPEL', 'Rappel : retour de prêt attendu'), ('PRET_RETARD', 'Prêt en retard'), ('ALERTE_DUA', 'DUA échéant dans 30 jours'), ('DUA_ECHUE', 'DUA échue — action requise'), ('INTEGRITE_KO', 'Alerte intégrité fichier'), ('RECHERCHE_RECUE', 'Nouvelle demande de recherche documentaire'), ('RECHERCHE_ACCORDEE', 'Recherche traitée — document trouvé'), ('RECHERCHE_REFUSEE', 'Recherche — document non trouvé')], max_length=30, verbose_name='Type'),
        ),
    ]
