# Generated by Django 6.0.3 on 2026-03-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0012_bordereau_versement_exercice_depots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereauversement',
            name='exercice',
            field=models.IntegerField(blank=True, db_index=True, help_text='Année budgétaire — auto-détecté depuis les dates de dépôts.', null=True, verbose_name='Exercice (année)'),
        ),
    ]
