# Generated by Django 6.0.3 on 2026-03-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du département / service')),
                ('type', models.CharField(choices=[('DIRECTION', 'Direction et gouvernance'), ('PEDAGOGIQUE', 'Pédagogique'), ('SCIENTIFIQUE', 'Scientifique et technique'), ('ADMINISTRATIF', 'Administratif'), ('SUPPORT', 'Support et logistique')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Département / Service',
                'verbose_name_plural': 'Départements / Services',
                'ordering': ['type', 'nom'],
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='service',
        ),
        migrations.AddField(
            model_name='customuser',
            name='departement',
            field=models.ForeignKey(blank=True, help_text="Service de rattachement de l'utilisateur.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.departement', verbose_name='Département / Service'),
        ),
    ]
